version: "3.1"
services:
  redis:
    image: "redis:latest"
    
    restart: always

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      REDIS_DNS: redis
    depends_on:
      - redis

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      BACKEND_DNS: backend
    depends_on:
      - redis
      - backend
    ports:
      - "8080:8080"