name: cookie-pipeline
on: 
  push:
    branches: 
    - "03-automation"
  pull_request:
    branches:
    - "main"
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Main-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: go build -v frontend/main_test.go

  
