name: cookie-pipeline
on: 
  push:
    branches: 
    - "03-automation"
    - "03-container-registry"
  pull_request:
    branches:
    - "main"
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Main-App-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run-App-Test
      run: go build -v frontend/main_test.go
 

  Build_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build frontend image
        run: docker image build -t nadineml/fortune-cookie-frontend ./frontend

      - name: Push frontend image
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: nadineml/fortune-cookie-frontend
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
