name: hello-world
on: 
  push:
    branches: 
    - "03-automation"
  pull_request:
    branches:
    - "main"
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"