name: cookie-pipeline
on: 
  push:
    branches: 
    - "03-automation"
    - "03-container-registry"
  pull_request:
    branches:
    - "main"
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Main-App-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run-App-Test
      run: go build -v frontend/main_test.go
  
  Docker-compose-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the stack
      run: docker-compose up -d
    - name: Test redis
      run: docker run --network container:redis appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
    - name: Test backend
      run: docker run --network container:backend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
    - name: Test frontend
      run: docker run --network container:frontend appropriate/curl -s --retry 10 --retry-connrefused http://localhost:5000/
