name: hello-world
on: 
  push:
    branches: 
    - "03-automation"
  pull_request:
    branches:
    - "main"
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: go build -v frontend/main_test.go

  
