name: cookie-pipeline
on: 
  push:
    branches: 
    - "03-automation"
    - "03-container-registry"
  pull_request:
    branches:
    - "main"
env: # Set the secret as an input
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Main-App-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run-App-Test
      run: go build -v frontend/main_test.go

  
  Clone-down:
    name: Clone down repo
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Repo
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
  
  Docker-image:
    runs-on: ubuntu-latest
    needs: Clone-down
    steps:
    - name: Compose docker
      run: docker-compose up -d
    - name: push docker
      run: chmod +x ci/push-docker.sh && ci/push-docker.sh
        
